# Generated by Django 5.2.14 on 2026-05-21 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Savol matni')),
                ('img', models.ImageField(blank=True, null=True, upload_to='certificate_questions/', verbose_name='Savol rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Sertifikat savoli',
                'verbose_name_plural': 'Sertifikat savollari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fan nomi')),
                ('img', models.ImageField(blank=True, null=True, upload_to='certificate_subjects/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Sertifikat fani',
                'verbose_name_plural': 'Sertifikat fanlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificateChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Variant matni')),
                ('img', models.ImageField(blank=True, null=True, upload_to='certificate_choices/', verbose_name='Variant rasmi')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='certificates.certificatequestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Sertifikat varianti',
                'verbose_name_plural': 'Sertifikat variantlari',
            },
        ),
        migrations.AddField(
            model_name='certificatequestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='certificates.certificatesubject', verbose_name='Fan'),
        ),
        migrations.CreateModel(
            name='CertificateAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Jami savollar')),
                ('correct_answers', models.PositiveIntegerField(verbose_name="To'g'ri javoblar")),
                ('score', models.PositiveIntegerField(verbose_name="Ball (1 to'g'ri = 1 ball)")),
                ('score_percent', models.FloatField(verbose_name='Natija (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yechilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_attempts', to='certificates.certificatesubject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Sertifikat test urinishi',
                'verbose_name_plural': 'Sertifikat test urinishlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
