# Generated by Django 5.2.14 on 2026-05-21 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_choice_text_alter_question_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Jami savollar')),
                ('correct_answers', models.PositiveIntegerField(verbose_name="To'g'ri javoblar")),
                ('score_percent', models.FloatField(verbose_name='Natija (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yechilgan vaqt')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='quizzes.subject', verbose_name='Fan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
