# Generated by Django 5.2.14 on 2026-05-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_test_price', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12, verbose_name="DTM Test yechish narxi (so'm)")),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Test narxi (so'm)"),
        ),
    ]
