# Generated by Django 5.2.14 on 2026-05-21 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('img', models.ImageField(blank=True, null=True, upload_to='universities/', verbose_name='Rasm')),
                ('rating', models.BigIntegerField(default=0, verbose_name='Reyting')),
            ],
            options={
                'verbose_name': 'Universitet',
                'verbose_name_plural': 'Universitetlar',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('min_score', models.BigIntegerField(default=0, verbose_name='Minimal ball')),
                ('grant_score', models.BigIntegerField(default=0, verbose_name='Grant ball')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='universities.university', verbose_name='Universitet')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['name'],
            },
        ),
    ]
