# Generated by Django 5.2.14 on 2026-05-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Veb-sayt'),
        ),
    ]
