# Generated by Django 5.2.14 on 2026-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokatsiya'),
        ),
        migrations.AddField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('state', 'Davlat'), ('private', 'Xususiy')], default='state', max_length=20, verbose_name='Turi'),
        ),
    ]
