# Generated by Django 5.2.14 on 2026-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_location_university_university_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='max_contract',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Maksimal kontrakt'),
        ),
        migrations.AddField(
            model_name='university',
            name='min_contract',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Minimal kontrakt'),
        ),
    ]
