# Generated by Django 5.2.14 on 2026-05-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_university_max_contract_university_min_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, choices=[('tashkent_city', 'Toshkent shahri'), ('tashkent', 'Toshkent viloyati'), ('andijan', 'Andijon viloyati'), ('bukhara', 'Buxoro viloyati'), ('fergana', "Farg'ona viloyati"), ('jizzakh', 'Jizzax viloyati'), ('khorezm', 'Xorazm viloyati'), ('namangan', 'Namangan viloyati'), ('navoiy', 'Navoiy viloyati'), ('kashkadarya', 'Qashqadaryo viloyati'), ('surkhandarya', 'Surxondaryo viloyati'), ('sirdarya', 'Sirdaryo viloyati'), ('samarkand', 'Samarqand viloyati'), ('karakalpakstan', "Qoraqalpog'iston Respublikasi")], max_length=50, null=True, verbose_name='Lokatsiya'),
        ),
    ]
