# Generated by Django 5.2.14 on 2026-05-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_alter_university_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='grant_score',
            field=models.FloatField(default=0.0, verbose_name='Grant ball'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='min_score',
            field=models.FloatField(default=0.0, verbose_name='Minimal ball'),
        ),
    ]
